version: '3.9'
name: 'edremit-backend'
services:
  # Monolitik backend servisiniz
  backend:
    build: ./backend
    container_name: backend_monolith
    restart: unless-stopped
    environment:
      - DB_HOST=osm_postgres_container
      - DB_PORT=5432
      - DB_NAME=edremit_maks
      - DB_USER=postgres
      - DB_PASSWORD=123
    networks:
      - backend-network
      - osm-db-network

  # Yeni location servisi
  location-service:
    build: ./location-service
    container_name: location_service
    restart: unless-stopped
    environment:
      - DB_HOST=osm_postgres_container
      - DB_PORT=5432
      - DB_NAME=edremit_maks
      - DB_USER=postgres
      - DB_PASSWORD=123
    networks:
      - backend-network
      - osm-db-network
      
  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
      - location-service
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network
    driver: bridge
  osm-db-network:
    external: true